### ISSUE TITLE
Drive ID

### ISSUE THREAD

**Issue by aardvarkl** [ngandrass/truenas-spindown-timer#10]
I notice you are using /dev/id to identify devices.
TrueNAS can change these around if the drive topology changes

Surely this should be using GPTID rtather than /dev/????

**Comment by ngandrass** [comment]
I did a quick check. Both `smartctl` and `camcontrol` are unable to work with GPTIDs directly. It should be possible to create a mapping using the output of `glabel status`. This, however is tied to device partitions instead of drives themselves. Example output:

`root@nas:/ # glabel status
                                      Name  Status  Components
gptid/afe576a5-8d03-11e3-b9b5-bc5ff4a7137f     N/A  ada0p2
gptid/80ea165f-14e3-11e8-b09e-bc5ff4a7137f     N/A  ada1p2
gptid/e10c13e3-757b-11ec-bdb2-bc5ff4a7137f     N/A  ada2p2
gptid/b2396f4d-8d03-11e3-b9b5-bc5ff4a7137f     N/A  ada3p2
gptid/3d2c322d-757d-11ec-bdb2-bc5ff4a7137f     N/A  ada4p2
gptid/b303267e-8d03-11e3-b9b5-bc5ff4a7137f     N/A  ada5p2
gptid/b3cb610b-8d03-11e3-b9b5-bc5ff4a7137f     N/A  ada6p2
gptid/529e2314-3826-11e7-a9df-bc5ff4a7137f     N/A  ada7p2`

I could use a list of GPTIDs to get the partition and derive the drive identifier from it. This however seems a bit error-prone to me.

Spindown is more or less only relevant for home use (correct me if I'm wrong :)). I don't expect a lot of disk changes with such setups. It surely would be the cleaner way to used GPTIDs but it also makes configuration less convenient in my opinion. Do you think that these drawbacks outweigh the benefit of not needing to adjust device identifiers after topology changes?

**Comment by gpatkinson** [comment]
my /dev/id's actually change with reboot sometimes (I actually didn't realize this until I started playing with this script). The pools still associate the proper drives but the sdX values can change. I'm on Bluefin 22.12

**Comment by ngandrass** [comment]
Hey @aardvarkl and @gpatkinson,

I pushed a beta version of a pool-based operation mode in #14. Please check it out and test if this solves your problems when you have some time.

Thanks! :+1:

**Comment by gpatkinson** [comment]
Nice! Will try it out in the next few days. Thanks for all your work on this project.

**Comment by ngandrass** [comment]
As stated in #14, version 2.1.0 implements the GPTID / partuuid based disk identification. I'll close this issue for now :)
