### ISSUE TITLE
Running three times?

### ISSUE THREAD

**Issue by sebirdman** [ngandrass/truenas-spindown-timer#17]
I've setup this script to automatically run as directed in the instructions at post init

when i run `ps -aux` i see three instances of the script:

```
   7286 ?        S      0:00 /bin/sh -c /root/spindown_timer.sh -t 3600 -p 600
   7287 ?        S      0:00 bash /root/spindown_timer.sh -t 3600 -p 600
   7340 ?        S      0:00 bash /root/spindown_timer.sh -t 3600 -p 600
```

Is this normal?

**Comment by ngandrass** [comment]
Yes, this behavior is normal. The script spawns multiple shell sub-processes while waiting for the `iostat` call to finish and during evaluation. This is due to the nature of how bash handles capture of external process output.

This is how it looks on one of my systems (using `htop`):
![image](https://user-images.githubusercontent.com/326180/210097190-c3a16546-87b3-4be8-b541-ded0337e1d30.png)

**Comment by sebirdman** [comment]
That makes sense! thanks!
